// Generated by CoffeeScript 1.7.1
$(function() {
  return window.render = function(template_name, target, data) {
    return dust.render(template_name, data, function(err, out) {
      return $(target).html(out);
    });
  };
});
