// Generated by CoffeeScript 1.7.1
$(function() {
  var api;
  render('nav', '.main-nav', {
    app_name: "Memorisation Admin",
    pages: [
      {
        name: "Edit Content",
        href: "#EditContent"
      }
    ]
  });
  api = "/api/index.php/api/list_targets";
  return $.getJSON(api).then(function(data) {
    render('levels_page', '.main-content', null);
    return render('level_list', '.levels', data);
  }).fail(function(err) {
    return console.error(err);
  });
});
